name: mvn deploy
on:
  issue_comment:
    types: [created]

jobs:
  mvn-deploy:
    uses: tradeshift/actions-workflow-maven/.github/workflows/comment-mvn-deploy.yml@v1
    with:
      java-version: 11
      maven-version: '3.6.3'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      maven-ca-cert-b64: ${{ secrets.MTLS_CACERT }}
      maven-keystore-p12-b64: ${{ secrets.MAVEN_P12 }}
      maven-keystore-password: ${{ secrets.MAVEN_P12_PASSWORD }}
      maven-settings-b64: ${{ secrets.MAVEN_SETTINGS }}
      maven-security-settings-b64: ${{ secrets.MAVEN_SECURITY }}
